[project]
name = "apifast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abdkad123", email = "akaddoura123@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.8.0",
    "python-dotenv>=1.2.2",
    "uvicorn[standard]>=0.52.0",
]

[project.scripts]
apifast = "apifast:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
